# Generated by Django 2.2.25 on 2021-12-21 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211221_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 21, 20, 43, 8, 19412), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 21, 20, 43, 8, 19412), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 21, 20, 43, 8, 19412), verbose_name='Добавлен'),
        ),
    ]
