# Generated by Django 2.2.25 on 2021-12-21 21:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20211221_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 15, 30, 270281), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 15, 30, 272273), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 15, 30, 270281), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 15, 30, 271276), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='sup',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 15, 30, 271276), verbose_name='Добавлен'),
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='posted', verbose_name='Введите ваш номер телефона и как к вам обращаться')),
                ('description', models.TextField(verbose_name='Введите адрес доставки (город, улица, дом)')),
                ('content', models.TextField(verbose_name='Напишите, что вы хотите заказать, и ваши личные пожелания к заказу')),
                ('posted', models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 0, 15, 30, 271276), verbose_name='Добавлен')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'заказы',
                'verbose_name_plural': 'заказы',
                'db_table': 'zakazposts',
                'ordering': ['-posted'],
            },
        ),
    ]
