# Generated by Django 2.2.25 on 2021-12-21 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211222_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 16, 51, 543263), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 16, 51, 545257), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 16, 51, 543263), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 16, 51, 544259), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='sup',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 16, 51, 543263), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='content',
            field=models.TextField(verbose_name='Подробности заказа'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='description',
            field=models.TextField(verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 16, 51, 544259), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='title',
            field=models.CharField(max_length=100, unique_for_date='posted', verbose_name='Номер телефона клиента и как к нему обращаться'),
        ),
    ]
