# Generated by Django 2.2.25 on 2021-12-21 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 18, 44, 777692), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 18, 44, 779651), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 18, 44, 777692), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 18, 44, 778687), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='sup',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 18, 44, 778687), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 1, 18, 44, 779651), verbose_name='Добавлен'),
        ),
    ]
