# Generated by Django 2.2.25 on 2021-12-22 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211222_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentz',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='commentz',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Ваше имя'),
        ),
        migrations.AddField(
            model_name='commentz',
            name='phone',
            field=models.CharField(default='', max_length=100, verbose_name='Ваш телефон'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 22, 21, 35, 638080), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 22, 21, 35, 640074), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='commentz',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 22, 21, 35, 641070), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 22, 21, 35, 638080), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 22, 21, 35, 639077), verbose_name='Добавлен'),
        ),
        migrations.AlterField(
            model_name='sup',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2021, 12, 22, 22, 21, 35, 639077), verbose_name='Добавлен'),
        ),
    ]
